# Jake 1.0.7 - A Servant for Lilly     (compiled on: Apr 14 2019 at: 23:19:40)

TEXFILE      := test.tex
BASENAME     := $(basename $(TEXFILE))
PDFFILE      := $(addsuffix .pdf,$(basename $(TEXFILE)))
LATEXARGS    := -shell-escape -enable-write18 -interaction=batchmode
## Directories used for INPUT and OUTPUT Files 
OUTPUTDIR    := ./$(BASENAME)-OUT/
INPUTDIR     := ./
BOXMODES     := DEFAULT                       ## Seperator: ' '
CLEANTARGETS := log aux out ind bbl blg lof lot toc idx acn acr alg glg glo gls fls fdb_latexmk auxlock md5 SATZE ZSM UB TOP listing upa ilg TOPIC 
NAMEPREFIX   :=                               ## Immer

## Makefile/General settings
_LILLYARGS   :=  \\\providecommand{\\\LILLYxDOCUMENTNAME{$(TEXFILE)}} $(DEBUG) \\\providecommand{\\\LILLYxPATH}{${INPUTDIR}} \\input{$(INPUTDIR)$(TEXFILE)} 

JOBCOUNT     := 2                             ## <= CPU_COUNT! 


define LILLYxCompile = 
    @echo LOGFILE: $(date +'%d.%m.%Y %H:%M:%S') > $(OUTPUTDIR)LILLY_COMPILE.log 2>&1
    for bm in $(BOXMODES); do \
    @pdflatex -jobname $(BASENAME) $(LATEXARGS) $(_LILLYARGS) ${2}\\\providecommand{\\\LILLYxBOXxMODE}{$$bm}\\\providecommand{\\\LILLYxPDFNAME}{${1}} >> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1\
    @pdflatex -jobname $(BASENAME) $(LATEXARGS) $(_LILLYARGS) ${2}\\\providecommand{\\\LILLYxBOXxMODE}{$$bm}\\\providecommand{\\\LILLYxPDFNAME}{${1}} >> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1\
    @pdflatex -jobname $(BASENAME) $(LATEXARGS) $(_LILLYARGS) ${2}\\\providecommand{\\\LILLYxBOXxMODE}{$$bm}\\\providecommand{\\\LILLYxPDFNAME}{${1}} >> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1\
; done;
    $(call LILLYxClean)
endef
define LILLYxClean = 
    for fd in $(CLEANTARGETS); do rm -f *.$$fd; done;
endef
default: $(INPUTDIR)$(TEXFILE)
@echo "	\033[38;2;255;191;0mGeneriere Standart-Version($(BOXMODE)) der Latex-Datei: "$(TEXFILE)"...\033[m"
	$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{FALSE}))
print: $(INPUTDIR)$(TEXFILE)
@echo "	\033[38;2;255;191;0mGeneriere Druck-Version($(BOXMODE)) der Latex-Datei: "$(TEXFILE)"...\033[m"
	$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)$(PDFFILE),\\providecommand\\LILLYxMODE{print}\\providecommand\\LILLYxMODExEXTRA{FALSE}))
