# Jake 1.0.7 - A Servant for Lilly     (compiled on: Apr 13 2019 at: 21:03:17)

TEXFILE      := test.tex
BASENAME     := $(basename $(TEXFILE))
PDFFILE      := $(addsuffix .pdf,$(basename $(TEXFILE)))
LATEXARGS    := -shell-escape -enable-write18 -interaction=batchmode
## Directories used for INPUT and OUTPUT Files 
OUTPUTDIR    := ./$(BASENAME)-OUT/
INPUTDIR     := ./
BOXMODES     := DEFAULT                       ## Seperator: ' '
CLEANTARGETS := log aux out ind bbl blg lof lot toc idx acn acr alg glg glo gls fls fdb_latexmk auxlock md5 SATZE ZSM UB TOP listing upa ilg TOPIC 
NAMEPREFIX   :=                               ## Immer

## Makefile/General settings
_LILLYARGS   :=  \\\providecommand{\\\LILLYxDOCUMENTNAME{$(TEXFILE)}} $(DEBUG) \\\providecommand{\\\LILLYxPATH}{${INPUTDIR}} \\input{$(INPUTDIR)$(TEXFILE)} 

JOBCOUNT     := 2                             ## <= CPU_COUNT! 


define LILLYxCompile = 
@pdflatex -jobname $(BASENAME) $(LATEXARGS) $(_LILLYARGS) ${2}\\\providecommand{\\\LILLYxPDFNAME}{${1}}
@pdflatex -jobname $(BASENAME) $(LATEXARGS) $(_LILLYARGS) ${2}\\\providecommand{\\\LILLYxPDFNAME}{${1}}
@pdflatex -jobname $(BASENAME) $(LATEXARGS) $(_LILLYARGS) ${2}\\\providecommand{\\\LILLYxPDFNAME}{${1}}
endef
