all:
	mvn clean install && java -cp target/lilly-jake-framework-1.0.10-DEVELOPMENT-shaded.jar de.eagle.lillyjakeframework.Jake 
run: 
	java -cp target/lilly-jake-framework-1.0.10-DEVELOPMENT-shaded.jar de.eagle.lillyjakeframework.Jake

clean:
	mvn clean
